export const FIELD_MISSION_CATALOG: Record<string, { lessonXP: number; description: [string, string]; steps: Array<[string, string]>; prompt: [string, string]; kinds: Array<'camera' | 'screenshot' | 'text'> }> = {
  // SMART MONEY & CAPITAL (learn-money-01..05)
  'learn-money-01': { lessonXP: 120, description: ['Separa hoy tu colchón del capital disponible y deja una regla visible.', 'Separate your buffer from available capital today and leave a visible rule.'], steps: [['Abre tu app bancaria o presupuesto.', 'Open your bank or budgeting app.'], ['Etiqueta el colchón y el excedente.', 'Label the buffer and surplus.'], ['Guarda una captura o explica la regla aplicada.', 'Save a screenshot or explain the applied rule.']], prompt: ['La evidencia debe mostrar una separación o regla concreta, sin exponer números sensibles.', 'Evidence must show a concrete separation or rule without exposing sensitive numbers.'], kinds: ['screenshot', 'text'] },
  'learn-money-02': { lessonXP: 130, description: ['Configura un aporte recurrente real o simulado.', 'Configure a real or simulated recurring contribution.'], steps: [['Abre tu broker, simulador o calendario.', 'Open your broker, simulator, or calendar.'], ['Configura monto y frecuencia.', 'Set amount and frequency.'], ['Captura la confirmación sin datos privados.', 'Capture confirmation without private data.']], prompt: ['Muestra monto, frecuencia y fecha de inicio.', 'Show amount, frequency, and start date.'], kinds: ['camera', 'screenshot', 'text'] },
  'learn-money-03': { lessonXP: 140, description: ['Compara dos ETF y documenta cuál supera tu filtro.', 'Compare two ETFs and document which one passes your filter.'], steps: [['Busca dos fondos comparables.', 'Find two comparable funds.'], ['Registra índice y ratio de gastos.', 'Record index and expense ratio.'], ['Selecciona uno con una razón verificable.', 'Choose one with a verifiable reason.']], prompt: ['La prueba debe incluir dos opciones y una decisión.', 'Proof must include two options and one decision.'], kinds: ['screenshot', 'text'] },
  'learn-money-04': { lessonXP: 150, description: ['Programa tu regla DCA en un sistema que te la recuerde o ejecute.', 'Schedule your DCA rule in a system that reminds or executes it.'], steps: [['Elige broker, calendario o recordatorio.', 'Choose broker, calendar, or reminder.'], ['Programa monto y fecha.', 'Schedule amount and date.'], ['Captura la configuración.', 'Capture the setup.']], prompt: ['Muestra una recurrencia concreta; puedes ocultar saldos.', 'Show a concrete recurrence; balances may be hidden.'], kinds: ['camera', 'screenshot'] },
  'learn-money-05': { lessonXP: 170, description: ['Escribe y guarda tu regla de riesgo antes de la próxima operación.', 'Write and save your risk rule before the next trade.'], steps: [['Define pérdida máxima.', 'Define maximum loss.'], ['Define tamaño y salida.', 'Define size and exit.'], ['Guarda la regla en tu bitácora.', 'Save the rule in your journal.']], prompt: ['Incluye pérdida máxima y condición de salida.', 'Include maximum loss and exit condition.'], kinds: ['screenshot', 'text'] },

  // AI & AUTOMATION (learn-ai-01..05)
  'learn-ai-01': { lessonXP: 120, description: ['Ejecuta tu prompt de cuatro bloques en un modelo y conserva el resultado.', 'Run your four-block prompt in a model and keep the result.'], steps: [['Copia la plantilla.', 'Copy the template.'], ['Ejecútala con una tarea real.', 'Run it on a real task.'], ['Captura prompt y salida útil.', 'Capture the prompt and useful output.']], prompt: ['La evidencia debe mostrar que el prompt fue ejecutado.', 'Evidence must show that the prompt was executed.'], kinds: ['screenshot', 'text'] },
  'learn-ai-02': { lessonXP: 130, description: ['Usa tu paquete de contexto para mejorar una respuesta real.', 'Use your context pack to improve a real response.'], steps: [['Ejecuta una petición sin contexto.', 'Run a request without context.'], ['Añade tu paquete de tres capas.', 'Add your three-layer context pack.'], ['Documenta la diferencia útil.', 'Document the useful difference.']], prompt: ['Compara antes y después con una diferencia concreta.', 'Compare before and after with one concrete difference.'], kinds: ['screenshot', 'text'] },
  'learn-ai-03': { lessonXP: 140, description: ['Aplica tu regla de ruteo a una tarea repetitiva esta semana.', 'Apply your routing rule to one repetitive task this week.'], steps: [['Elige una tarea real.', 'Choose a real task.'], ['Asigna modelo y aprobación.', 'Assign model and approval.'], ['Ejecuta una prueba.', 'Run one test.']], prompt: ['Muestra tarea, ruta elegida y resultado de la prueba.', 'Show task, selected route, and test result.'], kinds: ['screenshot', 'text'] },
  'learn-ai-04': { lessonXP: 150, description: ['Configura el primer paso de tu flujo trigger-transform-action.', 'Configure the first step of your trigger-transform-action workflow.'], steps: [['Abre Make, Zapier, n8n o equivalente.', 'Open Make, Zapier, n8n, or equivalent.'], ['Configura trigger y una acción de prueba.', 'Configure a trigger and one test action.'], ['Ejecuta y captura el log.', 'Run and capture the log.']], prompt: ['La prueba debe mostrar un trigger ejecutado y su salida.', 'Proof must show an executed trigger and its output.'], kinds: ['camera', 'screenshot'] },
  'learn-ai-05': { lessonXP: 170, description: ['Implementa un límite real en tu agente o automatización.', 'Implement one real limit in your agent or automation.'], steps: [['Elige una acción de riesgo.', 'Choose one risky action.'], ['Añade aprobación o límite.', 'Add approval or a limit.'], ['Prueba que el agente se detenga.', 'Test that the agent stops.']], prompt: ['Muestra el guardrail y una prueba de su comportamiento.', 'Show the guardrail and a test of its behavior.'], kinds: ['screenshot', 'text'] },

  // VIRAL GROWTH & MARKETING (learn-growth-01..05)
  'learn-growth-01': { lessonXP: 120, description: ['Publica o programa una pieza usando tu gancho de tres segundos.', 'Publish or schedule a piece using your three-second hook.'], steps: [['Inserta el gancho al inicio.', 'Place the hook at the opening.'], ['Publica o programa la pieza.', 'Publish or schedule the piece.'], ['Captura la publicación o borrador programado.', 'Capture the post or scheduled draft.']], prompt: ['La evidencia debe mostrar el gancho dentro de una pieza real.', 'Evidence must show the hook inside a real piece.'], kinds: ['camera', 'screenshot', 'text'] },
  'learn-growth-02': { lessonXP: 130, description: ['Contacta a tres personas que vivan el momento de dolor definido.', 'Contact three people who experience the defined pain moment.'], steps: [['Escribe una pregunta neutral.', 'Write one neutral question.'], ['Envía tres mensajes.', 'Send three messages.'], ['Captura los envíos ocultando datos privados.', 'Capture sends while hiding private data.']], prompt: ['Muestra tres acciones de contacto o un reporte específico.', 'Show three outreach actions or a specific report.'], kinds: ['screenshot', 'text'] },
  'learn-growth-03': { lessonXP: 140, description: ['Presenta tu oferta mejorada a una persona real.', 'Present your improved offer to one real person.'], steps: [['Reescribe la promesa.', 'Rewrite the promise.'], ['Añade prueba o reduce espera.', 'Add proof or reduce delay.'], ['Envía la oferta y documenta la reacción.', 'Send the offer and document the reaction.']], prompt: ['La prueba debe mostrar una oferta enviada o publicada.', 'Proof must show a sent or published offer.'], kinds: ['screenshot', 'text'] },
  'learn-growth-04': { lessonXP: 150, description: ['Graba y publica o programa tu guion de seis segundos.', 'Record and publish or schedule your six-second script.'], steps: [['Graba una toma completa.', 'Record one complete take.'], ['Publica o programa sin sobreeditar.', 'Publish or schedule without over-editing.'], ['Captura el resultado.', 'Capture the result.']], prompt: ['Muestra el clip publicado, programado o exportado.', 'Show the published, scheduled, or exported clip.'], kinds: ['camera', 'screenshot'] },
  'learn-growth-05': { lessonXP: 170, description: ['Distribuye una misma tesis en tres formatos reales.', 'Distribute one thesis in three real formats.'], steps: [['Publica la pieza principal.', 'Publish the primary piece.'], ['Adapta a dos canales adicionales.', 'Adapt it to two additional channels.'], ['Registra enlaces o capturas.', 'Record links or screenshots.']], prompt: ['La evidencia debe identificar tres adaptaciones de una tesis.', 'Evidence must identify three adaptations of one thesis.'], kinds: ['screenshot', 'text'] },

  // DATA SCIENCE & DECISIONS (learn-data-01..05)
  'learn-data-01': { lessonXP: 120, description: ['Audita una métrica de tu negocio o trabajo y filtra correlación de causalidad.', 'Audit a business or work metric and filter correlation from causation.'], steps: [['Identifica una métrica o correlación habitual.', 'Identify a frequent metric or correlation.'], ['Evalúa la posible variable confusora oculta.', 'Evaluate potential hidden confounding variables.'], ['Documenta la prueba de control o regla resultante.', 'Document the control test or resulting rule.']], prompt: ['Muestra la métrica analizada y la conclusión causal o regla fijada.', 'Show the analyzed metric and the causal conclusion or locked rule.'], kinds: ['screenshot', 'text'] },
  'learn-data-02': { lessonXP: 130, description: ['Define tu métrica North Star emparejada con su contra-métrica de calidad.', 'Define your North Star metric paired with its quality counter-metric.'], steps: [['Anota tu métrica North Star de intercambio de valor real.', 'Write your North Star metric measuring real value exchange.'], ['Define una contra-métrica que impida optimizaciones destructivas.', 'Define a counter-metric preventing destructive optimization.'], ['Guarda ambas métricas en tu panel u hoja de seguimiento.', 'Save both metrics to your dashboard or tracking sheet.']], prompt: ['La evidencia debe mostrar la North Star y su contra-métrica correspondiente.', 'Evidence must show the North Star and its corresponding counter-metric.'], kinds: ['screenshot', 'text'] },
  'learn-data-03': { lessonXP: 140, description: ['Registra hipótesis y tamaño de muestra antes de lanzar un experimento.', 'Log hypothesis and sample size before launching an experiment.'], steps: [['Calcula el tamaño de muestra mínimo requerido.', 'Calculate the minimum required sample size.'], ['Fija por escrito la fecha estimada de cierre.', 'Lock in writing the estimated end date.'], ['Registra la regla de no declarar ganadores tempranos.', 'Record the rule against calling early winners.']], prompt: ['Muestra hipótesis, tamaño de muestra calculado y fecha de revisión.', 'Show hypothesis, calculated sample size, and review date.'], kinds: ['screenshot', 'text'] },
  'learn-data-04': { lessonXP: 150, description: ['Aplica una prueba de validación independiente para evitar sobreajuste.', 'Apply an independent validation test to avoid overfitting.'], steps: [['Selecciona una regla operativa o de ventas reciente.', 'Select a recent operational or sales rule.'], ['Pruébala contra 5 casos pasados independientes.', 'Test it against 5 independent past cases.'], ['Ajusta o confirma la regla según la evidencia.', 'Adjust or confirm the rule based on evidence.']], prompt: ['La evidencia debe comparar la regla contra casos de validación independientes.', 'Evidence must compare the rule against independent validation cases.'], kinds: ['screenshot', 'text'] },
  'learn-data-05': { lessonXP: 170, description: ['Dibuja y calcula un árbol de decisión para tu mayor dilema actual.', 'Draw and calculate a decision tree for your biggest current dilemma.'], steps: [['Plantea las dos ramas principales de acción.', 'Lay out the two primary action branches.'], ['Asigna probabilidades y valor esperado estimado.', 'Assign probabilities and estimated expected value.'], ['Documenta la decisión tomada con base en valor esperado.', 'Document the decision made based on expected value.']], prompt: ['Muestra el árbol o cálculo con probabilidades y rama seleccionada.', 'Show the tree or calculation with probabilities and selected branch.'], kinds: ['camera', 'screenshot', 'text'] },

  // MINDSET & STOICISM (learn-mindset-01..05)
  'learn-mindset-01': { lessonXP: 120, description: ['Escribe tu filtro estoico separando control directo de variables externas.', 'Write your stoic filter separating direct control from external variables.'], steps: [['Abre dos columnas: bajo mi control y fuera de mi control.', 'Open two columns: under my control and outside my control.'], ['Clasifica tu mayor fricción o preocupación actual.', 'Classify your primary current friction or concern.'], ['Define una acción física inmediata para lo que sí controlas.', 'Define one immediate physical action for what you control.']], prompt: ['Muestra las dos columnas y la acción física definida para lo controlable.', 'Show the two columns and the physical action defined for what is controllable.'], kinds: ['screenshot', 'text'] },
  'learn-mindset-02': { lessonXP: 130, description: ['Ejecuta un pre-mortem identificando los dos mayores riesgos de fallo.', 'Execute a pre-mortem identifying the two largest failure risks.'], steps: [['Imagina el fracaso de tu proyecto en tres meses.', 'Imagine project failure three months ahead.'], ['Anota las dos causas plausibles más probables.', 'Record the two most plausible root causes.'], ['Establece una contramedida preventiva para cada una.', 'Establish a preventive countermeasure for each.']], prompt: ['La prueba debe detallar riesgos identificados y contramedidas preventivas.', 'Proof must detail identified risks and preventive countermeasures.'], kinds: ['screenshot', 'text'] },
  'learn-mindset-03': { lessonXP: 140, description: ['Convierte un revés reciente en una mejora de tu sistema operativo.', 'Turn a recent setback into an upgrade for your operating system.'], steps: [['Identifica un error, rechazo o pérdida reciente.', 'Identify a recent mistake, rejection, or loss.'], ['Formula la lección permanente en una sola frase.', 'Formulate the permanent lesson in a single sentence.'], ['Aplica un cambio de sistema para evitar su repetición.', 'Apply a system tweak to prevent repetition.']], prompt: ['Muestra la lección extraída y el cambio de sistema aplicado.', 'Show the extracted lesson and the applied system tweak.'], kinds: ['screenshot', 'text'] },
  'learn-mindset-04': { lessonXP: 150, description: ['Reencuadra una situación tensa para extraer su ventaja asimétrica.', 'Reframe a tense situation to extract its asymmetric advantage.'], steps: [['Identifica un obstáculo o fuente de fricción actual.', 'Identify an active obstacle or source of friction.'], ['Pregúntate qué ventaja estratégica oculta te otorga.', 'Ask what hidden strategic advantage it hands you.'], ['Anota la nueva postura operativa y compórtate en base a ella.', 'Record the new operating posture and act accordingly.']], prompt: ['La evidencia debe mostrar el reencuadre y la postura operativa resultante.', 'Evidence must show the reframe and resulting operating posture.'], kinds: ['screenshot', 'text'] },
  'learn-mindset-05': { lessonXP: 170, description: ['Aplica inversión: lista cómo garantizar el fracaso y pon una barrera.', 'Apply inversion: list how to guarantee failure and erect a barrier.'], steps: [['Pregúntate cómo arruinar tu meta en 6 meses.', 'Ask how to ruin your objective in 6 months.'], ['Identifica las 3 conductas destructivas obvias.', 'Identify the 3 obvious destructive behaviors.'], ['Instala una barrera física o regla que bloquee la principal.', 'Install a physical barrier or rule blocking the primary one.']], prompt: ['Muestra la lista de inversión y la barrera preventiva implementada.', 'Show the inversion list and the implemented preventive barrier.'], kinds: ['screenshot', 'text'] },

  // PEAK PERFORMANCE & FOCUS (learn-perf-01..05)
  'learn-perf-01': { lessonXP: 120, description: ['Programa y ejecuta un bloque ininterrumpido de trabajo profundo.', 'Schedule and execute one uninterrupted deep work block.'], steps: [['Elige tu palanca más importante del día.', 'Choose your single highest-impact priority lever.'], ['Silencia notificaciones y retira distracciones.', 'Silence notifications and remove distractions.'], ['Ejecuta un bloque continuo de foco con cronómetro.', 'Execute a continuous focus block with a timer.']], prompt: ['La evidencia debe mostrar el bloque ejecutado y el avance en tu tarea prioritaria.', 'Evidence must show the executed block and progress on your priority task.'], kinds: ['camera', 'screenshot', 'text'] },
  'learn-perf-02': { lessonXP: 130, description: ['Diseña y ejecuta tu protocolo de desconexión y cierre de jornada.', 'Design and execute your workday shutdown and disconnect protocol.'], steps: [['Revisa tareas pendientes 15 minutos antes de cerrar.', 'Review open tasks 15 minutes prior to shutdown.'], ['Anota las 3 prioridades del día siguiente.', 'Record tomorrow\'s top 3 priorities.'], ['Ejecuta la frase de cierre y desconecta dispositivos laborales.', 'Execute shutdown phrase and disconnect work devices.']], prompt: ['Muestra las 3 prioridades de mañana y el cierre de jornada registrado.', 'Show tomorrow\'s 3 priorities and the logged day shutdown.'], kinds: ['screenshot', 'text'] },
  'learn-perf-03': { lessonXP: 140, description: ['Elimina un paso de fricción previa en tu hábito más importante.', 'Eliminate one point of friction in your highest-leverage habit.'], steps: [['Identifica el hábito clave que te cuesta iniciar a diario.', 'Identify the key habit you struggle to initiate daily.'], ['Reduce su fricción previa para que tome menos de 30 segundos empezar.', 'Reduce prior friction so starting takes under 30 seconds.'], ['Documenta la preparación ambiental realizada.', 'Document the environmental setup created.']], prompt: ['Muestra la preparación del entorno o cambio que redujo la fricción.', 'Show the environment prep or tweak reducing starting friction.'], kinds: ['camera', 'screenshot', 'text'] },
  'learn-perf-04': { lessonXP: 150, description: ['Mapea y protege tus 3 horas biológicas de máximo rendimiento.', 'Map and protect your 3 peak biological cognitive hours.'], steps: [['Identifica tu ventana de mayor lucidez y energía mental.', 'Identify your window of highest clarity and mental energy.'], ['Bloquea ese horario en calendario sin reuniones ni llamadas.', 'Block that window on calendar free of meetings and calls.'], ['Relega tareas mecánicas a tu momento de menor energía.', 'Relegate mechanical tasks to your lower-energy window.']], prompt: ['La evidencia debe mostrar el bloque protegido en tu calendario o agenda.', 'Evidence must show the protected focus block on your calendar or schedule.'], kinds: ['screenshot', 'text'] },
  'learn-perf-05': { lessonXP: 170, description: ['Aplica la regla 5/25 de Buffett para blindar tus prioridades clave.', 'Apply Buffett\'s 5/25 rule to shield your top priorities.'], steps: [['Lista tus 20 objetivos o proyectos actuales.', 'List 20 current goals or active projects.'], ['Selecciona tus 5 prioridades absolutas y táchate las 15 secundarias.', 'Select your top 5 priorities and cross off the 15 secondary ones.'], ['Trata las 15 secundarias como lista de evitar a toda costa.', 'Treat the 15 secondary goals as an avoid-at-all-costs list.']], prompt: ['Muestra tus 5 prioridades seleccionadas y el compromiso de evitar distracciones.', 'Show your 5 selected priorities and commitment to avoid distractions.'], kinds: ['screenshot', 'text'] },

  // HISTORY & STRATEGY (learn-history-01..05)
  'learn-history-01': { lessonXP: 120, description: ['Evalúa el terreno táctico de tu mercado antes de competir de frente.', 'Assess tactical market terrain before entering direct attrition.'], steps: [['Identifica 3 puntos débiles donde competidores son lentos o costosos.', 'Identify 3 weak points where incumbents are slow or costly.'], ['Define tu oferta para posicionarte exclusivamente en ese terreno.', 'Position your offer exclusively on that asymmetric ground.'], ['Registra las reglas de evitación de choque frontal.', 'Record the rules avoiding frontal collision.']], prompt: ['La evidencia debe mostrar el mapa de terreno y la posición asimétrica elegida.', 'Evidence must show the terrain map and chosen asymmetric position.'], kinds: ['screenshot', 'text'] },
  'learn-history-02': { lessonXP: 130, description: ['Reforma tu presentación para neutralizar la objeción principal antes de que surja.', 'Reframe your presentation to neutralize the main objection before it surfaces.'], steps: [['Identifica la objeción recurrente más dura en tu propuesta.', 'Identify the recurring hardest objection to your proposal.'], ['Integra la respuesta dentro de tu apertura o página de destino.', 'Integrate the rebuttal directly into your opening or landing page.'], ['Prueba el nuevo encuadre en una interacción o borrador real.', 'Test the new framing in a real interaction or draft.']], prompt: ['Muestra el nuevo encuadre que aborda la objeción por adelantado.', 'Show the new framing addressing the objection upfront.'], kinds: ['screenshot', 'text'] },
  'learn-history-03': { lessonXP: 140, description: ['Diseña una maniobra de flanqueo hacia un nicho ignorado.', 'Design a flanking maneuver into an overlooked niche.'], steps: [['Localiza el segmento que los competidores grandes consideran insignificante.', 'Locate the segment large incumbents consider negligible.'], ['Adapta una propuesta hiperpersonalizada para ese nicho.', 'Tailor a hyper-specific proposition for that niche.'], ['Contacta a dos prospectos de ese nicho hoy.', 'Reach out to two prospects in that niche today.']], prompt: ['La prueba debe mostrar la propuesta de nicho o el contacto de flanqueo.', 'Proof must show the niche proposition or flanking outreach.'], kinds: ['screenshot', 'text'] },
  'learn-history-04': { lessonXP: 150, description: ['Fija un disparador observable para tomar decisiones bajo incertidumbre.', 'Set an observable trigger to make decisions under uncertainty.'], steps: [['Selecciona una decisión postergada por supuesta falta de información.', 'Select a delayed decision waiting on supposed missing data.'], ['Define el dato mínimo observable necesario (regla 40-70%).', 'Define the minimum observable data point needed (40-70% rule).'], ['Ejecuta la decisión si ya superas el umbral fijado.', 'Pull the trigger on the decision if threshold is already met.']], prompt: ['Muestra el disparador definido y la decisión ejecutada.', 'Show the defined trigger and the executed decision.'], kinds: ['screenshot', 'text'] },
  'learn-history-05': { lessonXP: 170, description: ['Audita y registra tu protocolo de disciplina táctica diaria.', 'Audit and record your daily tactical discipline protocol.'], steps: [['Anota tu protocolo no negociable de ejecución diaria.', 'Write down your non-negotiable daily execution protocol.'], ['Evalúa su cumplimiento estricto antes de medianoche.', 'Score strict adherence before midnight.'], ['Registra la victoria táctica del día en tu bitácora.', 'Log today\'s tactical victory in your journal.']], prompt: ['La evidencia debe mostrar el protocolo diario evaluado y completado.', 'Evidence must show the evaluated and completed daily protocol.'], kinds: ['screenshot', 'text'] },
};

